# Generated by Django 3.2.9 on 2021-12-12 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanchasFutbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('cantidadUsuarios', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'canchasfutbol',
            },
        ),
        migrations.CreateModel(
            name='CanchasPaddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('cantidadUsuarios', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'canchaspaddle',
            },
        ),
        migrations.CreateModel(
            name='CastorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GruposReserbas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.IntegerField()),
                ('fecha', models.DateField()),
                ('deporte', models.CharField(max_length=15)),
                ('contador', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Grupo de Recerbas',
                'db_table': 'gruposreserbas',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('cantidadUsuarios', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gym',
            },
        ),
        migrations.CreateModel(
            name='Pileta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('cantidadUsuarios', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pileta',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('precioUnidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precioTotal', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='ProductosVendidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantVendida', models.IntegerField(default=0)),
                ('fechaVenta', models.DateField(blank=True, null=True)),
                ('producto', models.ForeignKey(db_column='producto', on_delete=django.db.models.deletion.CASCADE, to='api.productos')),
            ],
            options={
                'verbose_name_plural': 'Productos Vendidos',
                'db_table': 'productosvendidos',
            },
        ),
        migrations.CreateModel(
            name='CycleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_user', models.IntegerField(default=1000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.castoruser')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('pagoAbonado', models.CharField(default='No', max_length=2)),
                ('totalPagar', models.IntegerField()),
                ('datos_usuario', models.ForeignKey(db_column='datos_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='datos_usuario', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(db_column='empleado', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('futbol', models.ForeignKey(blank=True, db_column='futbol', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.canchasfutbol')),
                ('grupo', models.ForeignKey(db_column='grupo', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.gruposreserbas')),
                ('gym', models.ForeignKey(blank=True, db_column='gym', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gym')),
                ('paddle', models.ForeignKey(blank=True, db_column='paddle', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.canchaspaddle')),
                ('pileta', models.ForeignKey(blank=True, db_column='pileta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pileta')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
    ]
