# Generated by Django 3.1 on 2021-05-12 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanchasFutbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('cantidadUsuarios', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CanchasFutbol',
            },
        ),
        migrations.CreateModel(
            name='CanchasPaddle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('cantidadUsuarios', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CanchasPaddle',
            },
        ),
        migrations.CreateModel(
            name='GruposReserbas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('deporte', models.CharField(max_length=15)),
                ('contador', models.IntegerField()),
            ],
            options={
                'db_table': 'GruposReserbas',
            },
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('cantidadUsuarios', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Gym',
            },
        ),
        migrations.CreateModel(
            name='Pileta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('cantidadUsuarios', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Pileta',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('precioUnidad', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductosVendidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantVendida', models.IntegerField()),
                ('fechaVenta', models.DateField()),
                ('empleado', models.ForeignKey(db_column='empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(db_column='producto', on_delete=django.db.models.deletion.CASCADE, to='api.productos')),
            ],
            options={
                'db_table': 'ProductosVendidos',
            },
        ),
    ]
