# Generated by Django 3.1 on 2021-05-12 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('formaPago', models.CharField(default='Efectivo', max_length=10)),
                ('totalPagar', models.IntegerField()),
                ('empleado', models.ForeignKey(db_column='empleado', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('futbol', models.ForeignKey(db_column='futbol', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.canchasfutbol')),
                ('grupo', models.ForeignKey(db_column='grupo', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.gruposreserbas')),
                ('gym', models.ForeignKey(db_column='gym', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gym')),
                ('paddle', models.ForeignKey(db_column='paddle', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.canchaspaddle')),
                ('pileta', models.ForeignKey(db_column='pileta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pileta')),
            ],
            options={
                'db_table': 'Clientes',
            },
        ),
    ]
